///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StevesGlobalBrowserDemo
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void OpenBrowser()
        {
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.edgewordstraining.co.uk/training-site/' with browser 'Chrome' in normal mode.");
            
            string browserToOpen = TestSuite.Current.Parameters["Browser"];
            //TestSuite.Current.Parameters["StevesParam"] = "StevePowell";
            
            
            Host.Current.OpenBrowser("http://www.edgewordstraining.co.uk/training-site/", browserToOpen, "", false, false, false, false, false, true);
        }

    }
}
