///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StevesGlobalBrowserDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the StevesGlobalBrowserDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f0e3e039-ab88-4c5a-bfa4-72410bc9a0c0")]
    public partial class StevesGlobalBrowserDemoRepository : RepoGenBaseFolder
    {
        static StevesGlobalBrowserDemoRepository instance = new StevesGlobalBrowserDemoRepository();

        /// <summary>
        /// Gets the singleton class instance representing the StevesGlobalBrowserDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("f0e3e039-ab88-4c5a-bfa4-72410bc9a0c0")]
        public static StevesGlobalBrowserDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public StevesGlobalBrowserDemoRepository() 
            : base("StevesGlobalBrowserDemoRepository", "/", null, 0, false, "f0e3e039-ab88-4c5a-bfa4-72410bc9a0c0", ".\\RepositoryImages\\StevesGlobalBrowserDemoRepositoryf0e3e039.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f0e3e039-ab88-4c5a-bfa4-72410bc9a0c0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class StevesGlobalBrowserDemoRepositoryFolders
    {
    }
#pragma warning restore 0436
}
